[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.21.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"